version: 2.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2019 Preview
configuration:
- Debug
- Test
- Deploy
platform: Any CPU
install:
- cmd: git submodule update --init --recursive
before_build:
- ps: nuget restore c:\projects\linqbridgevs\src\BridgeVs.sln
build:
  project: src\BridgeVs.sln
  parallel: true
  verbosity: normal
environment:
  LICENSE:
    secure: Xt89zh3/sBkKjzrExB+Qhyc6zuRNB0lQhj7RuPHrJ4s=
  COMPANY_NAME:
    secure: TE/EpwbShGrtiWBvkYKzNakaXglte8G723mXWPDjtP0=
test_script:
- ps: |
    if ($env:CONFIGURATION -eq "Test") 
    {
       $args = c:\projects\linqbridgevs\Lib\Typemock\TMockRunner.exe -deploy c:\projects\linqbridgevs\Lib\Typemock\AutoDeploy -register $env:COMPANY_NAME $env:LICENSE vstest.console.exe "Test\BridgeVs.UnitTest\bin\Test\BridgeVs.UnitTest.dll" /logger:Appveyor /TestCaseFilter:"TestCategory=UnitTest"
       Start-Process powershell -Verb runAs -ArgumentList '$args'
    }
